# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://appdev-projects.github.io/'
baseurl:             'learningjournal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Maxwell Longi
  url:               https://www.linkedin.com/in/maxwelllongi/
  email:             maxwell.longi@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
